# projectName/.github/draft-release.yml

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    label: 'feature'
  - title: 'Refactoring'
    label: 'refactor'
  - title: 'Fixes'
    label: 'bug'
  - title: 'Settings'
    label: 'setting'
    label: 'infra'
  - title: 'Etc'
    label: 'docs'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## 변경사항
  $CHANGES
